name: tudy
description: "A new Flutter project created with base MuonroiBuildingBlock.Flutter."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  dio: ^5.8.0+1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  hive: ^2.2.3
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  path_provider: ^2.1.5
  fluttertoast: ^8.2.12
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
