name: tudy
description: "A new Flutter project created with base MuonroiBuildingBlock.Flutter."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^14.8.1
  dio: ^5.8.0+1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  hive: ^2.2.3
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  path_provider: ^2.1.5
  fluttertoast: ^8.2.12
  flutter_riverpod: ^2.6.1
  logger: ^2.5.0
  flutter_svg: ^2.0.17
  table_calendar: ^3.1.3
  uuid: ^4.5.1
  collection: ^1.19.1
  shared_preferences: ^2.5.3
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
  generate: true
flutter_intl:
  enabled: true
